"""V4

Revision ID: 3fb10116b2c8
Revises: 626ed78eba0d
Create Date: 2023-09-26 17:56:45.953091

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '3fb10116b2c8'
down_revision = '626ed78eba0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
