"""V3

Revision ID: a8f4015a7cbb
Revises: 9d1cf2d606a2
Create Date: 2023-09-25 19:27:31.301574

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8f4015a7cbb'
down_revision = '9d1cf2d606a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
