"""V5

Revision ID: e6d9c59989cc
Revises: 3fb10116b2c8
Create Date: 2023-09-27 20:16:52.749273

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6d9c59989cc'
down_revision = '3fb10116b2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
